//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RVMS.Win.RvmsServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RvmsServices.IRvmsService")]
    public interface IRvmsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRvmsService/VratiOpstine", ReplyAction="http://tempuri.org/IRvmsService/VratiOpstineResponse")]
        RVMS.Model.Entities.Opstina[] VratiOpstine();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRvmsService/VratiStajalisteOpstine", ReplyAction="http://tempuri.org/IRvmsService/VratiStajalisteOpstineResponse")]
        RVMS.Model.DTO.StajalisteDTO[] VratiStajalisteOpstine(System.Nullable<int> idOpstine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRvmsService/VratiDaljinar", ReplyAction="http://tempuri.org/IRvmsService/VratiDaljinarResponse")]
        RVMS.Model.DTO.RelacijaDTO[] VratiDaljinar();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRvmsServiceChannel : RVMS.Win.RvmsServices.IRvmsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RvmsServiceClient : System.ServiceModel.ClientBase<RVMS.Win.RvmsServices.IRvmsService>, RVMS.Win.RvmsServices.IRvmsService {
        
        public RvmsServiceClient() {
        }
        
        public RvmsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RvmsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RvmsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RvmsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RVMS.Model.Entities.Opstina[] VratiOpstine() {
            return base.Channel.VratiOpstine();
        }
        
        public RVMS.Model.DTO.StajalisteDTO[] VratiStajalisteOpstine(System.Nullable<int> idOpstine) {
            return base.Channel.VratiStajalisteOpstine(idOpstine);
        }
        
        public RVMS.Model.DTO.RelacijaDTO[] VratiDaljinar() {
            return base.Channel.VratiDaljinar();
        }
    }
}
