//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RVMS.Win.Services.Stajalista {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.Stajalista.Stajalista")]
    public interface Stajalista {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Stajalista/VratiStajalista", ReplyAction="http://tempuri.org/Stajalista/VratiStajalistaResponse")]
        RVMS.Model.DTO.StajalisteDTO[] VratiStajalista(System.Nullable<int> idOpstine, System.Nullable<int> idMesta);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Stajalista/VratiStajalista", ReplyAction="http://tempuri.org/Stajalista/VratiStajalistaResponse")]
        System.IAsyncResult BeginVratiStajalista(System.Nullable<int> idOpstine, System.Nullable<int> idMesta, System.AsyncCallback callback, object asyncState);
        
        RVMS.Model.DTO.StajalisteDTO[] EndVratiStajalista(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StajalistaChannel : RVMS.Win.Services.Stajalista.Stajalista, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VratiStajalistaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public VratiStajalistaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public RVMS.Model.DTO.StajalisteDTO[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((RVMS.Model.DTO.StajalisteDTO[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StajalistaClient : System.ServiceModel.ClientBase<RVMS.Win.Services.Stajalista.Stajalista>, RVMS.Win.Services.Stajalista.Stajalista {
        
        private BeginOperationDelegate onBeginVratiStajalistaDelegate;
        
        private EndOperationDelegate onEndVratiStajalistaDelegate;
        
        private System.Threading.SendOrPostCallback onVratiStajalistaCompletedDelegate;
        
        public StajalistaClient() {
        }
        
        public StajalistaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StajalistaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StajalistaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StajalistaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<VratiStajalistaCompletedEventArgs> VratiStajalistaCompleted;
        
        public RVMS.Model.DTO.StajalisteDTO[] VratiStajalista(System.Nullable<int> idOpstine, System.Nullable<int> idMesta) {
            return base.Channel.VratiStajalista(idOpstine, idMesta);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginVratiStajalista(System.Nullable<int> idOpstine, System.Nullable<int> idMesta, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginVratiStajalista(idOpstine, idMesta, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public RVMS.Model.DTO.StajalisteDTO[] EndVratiStajalista(System.IAsyncResult result) {
            return base.Channel.EndVratiStajalista(result);
        }
        
        private System.IAsyncResult OnBeginVratiStajalista(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Nullable<int> idOpstine = ((System.Nullable<int>)(inValues[0]));
            System.Nullable<int> idMesta = ((System.Nullable<int>)(inValues[1]));
            return this.BeginVratiStajalista(idOpstine, idMesta, callback, asyncState);
        }
        
        private object[] OnEndVratiStajalista(System.IAsyncResult result) {
            RVMS.Model.DTO.StajalisteDTO[] retVal = this.EndVratiStajalista(result);
            return new object[] {
                    retVal};
        }
        
        private void OnVratiStajalistaCompleted(object state) {
            if ((this.VratiStajalistaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.VratiStajalistaCompleted(this, new VratiStajalistaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void VratiStajalistaAsync(System.Nullable<int> idOpstine, System.Nullable<int> idMesta) {
            this.VratiStajalistaAsync(idOpstine, idMesta, null);
        }
        
        public void VratiStajalistaAsync(System.Nullable<int> idOpstine, System.Nullable<int> idMesta, object userState) {
            if ((this.onBeginVratiStajalistaDelegate == null)) {
                this.onBeginVratiStajalistaDelegate = new BeginOperationDelegate(this.OnBeginVratiStajalista);
            }
            if ((this.onEndVratiStajalistaDelegate == null)) {
                this.onEndVratiStajalistaDelegate = new EndOperationDelegate(this.OnEndVratiStajalista);
            }
            if ((this.onVratiStajalistaCompletedDelegate == null)) {
                this.onVratiStajalistaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnVratiStajalistaCompleted);
            }
            base.InvokeAsync(this.onBeginVratiStajalistaDelegate, new object[] {
                        idOpstine,
                        idMesta}, this.onEndVratiStajalistaDelegate, this.onVratiStajalistaCompletedDelegate, userState);
        }
    }
}
