SET IDENTITY_INSERT [dbo].[Opstinas] ON
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (1, N'Ada', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (2, N'Bečej', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (3, N'Senta', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (4, N'Aleksandrovac', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (5, N'Aleksinac', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (6, N'Alibunar', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (7, N'Apatin', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (8, N'Aranđelovac', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (9, N'Arilje', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (10, N'Babušnica', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (11, N'Bajina Bašta', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (12, N'Batočina', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (13, N'Bač', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (14, N'Bačka Palanka', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (15, N'Bačka Topola', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (16, N'Bački Petrovac', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (17, N'Bela Palanka', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (18, N'Bela Crkva', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (19, N'Beograd-Barajevo', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (20, N'Beograd-Voždovac', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (21, N'Beograd-Grocka', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (22, N'Beograd-Zemun', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (23, N'Beograd-Lazarevac', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (24, N'Beograd-Mladenovac', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (25, N'Beograd-Novi Beograd', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (26, N'Beograd-Obrenovac', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (27, N'Beograd-Palilula', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (28, N'Beograd-Rakovica', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (29, N'Beograd-Savski Venac', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (30, N'Beograd-Sopot', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (31, N'Beograd-Stari Grad', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (32, N'Beograd-Surčin', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (33, N'Beograd-Čukarica', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (34, N'Beočin', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (35, N'Bečej', 0)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (36, N'Blace', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (37, N'Bogatić', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (38, N'Bojnik', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (39, N'Boljevac', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (40, N'Bor', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (41, N'Bosilegrad', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (42, N'Brus', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (43, N'Bujanovac', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (44, N'Valjevo', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (45, N'Varvarin', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (46, N'Velika Plana', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (47, N'Veliko Gradište', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (48, N'Vitina', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (49, N'Vladimirci', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (50, N'Vladičin Han', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (51, N'Vlasotince', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (52, N'Vranje', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (53, N'Vrbas', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (54, N'Vrnjačka Banja', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (55, N'Vršac', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (56, N'Vučitrn', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (57, N'Gadžin Han', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (58, N'Glogovac', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (59, N'Gnjilane', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (60, N'Golubac', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (61, N'Gora', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (62, N'Gornji Milanovac', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (63, N'Despotovac', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (64, N'Dečani', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (65, N'Dimitrovgrad', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (66, N'Doljevac', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (67, N'Đakovica', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (68, N'Žabalj', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (69, N'Žabari', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (70, N'Žagubica', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (71, N'Žitište', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (72, N'Žitorađa', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (73, N'Zaječar', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (74, N'Zvečan', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (75, N'Zrenjanin', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (76, N'Zubin Potok', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (77, N'Ivanjica', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (78, N'Inđija', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (79, N'Irig', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (80, N'Istok', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (81, N'Jagodina', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (82, N'Kanjiža', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (83, N'Kačanik', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (84, N'Kikinda', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (85, N'Kladovo', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (86, N'Klina', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (87, N'Knić', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (88, N'Knjaževac', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (89, N'Kovačica', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (90, N'Kovin', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (91, N'Kosjerić', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (92, N'Kosovo Polje', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (93, N'Kosovska Kamenica', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (94, N'Kosovska Mitrovica', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (95, N'Koceljeva', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (96, N'Kragujevac - grad', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (97, N'Kraljevo', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (98, N'Krupanj', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (99, N'Kruševac', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (100, N'Kula', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (101, N'Kuršumlija', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (102, N'Kučevo', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (103, N'Lajkovac', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (104, N'Lapovo', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (105, N'Lebane', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (106, N'Leposavić', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (107, N'Leskovac', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (108, N'Lipljan', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (109, N'Loznica', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (110, N'Lučani', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (111, N'Ljig', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (112, N'Ljubovija', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (113, N'Majdanpek', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (114, N'Mali Zvornik', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (115, N'Mali Iđoš', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (116, N'Malo Crniće', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (117, N'Medveđa', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (118, N'Merošina', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (119, N'Mionica', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (120, N'Negotin', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (121, N'Niš-Mediana', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (122, N'Niš-Niška Banja', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (123, N'Niš-Palilula', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (124, N'Niš-Pantelej', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (125, N'Niš-Crveni Krst', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (126, N'Nova Varoš', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (127, N'Nova Crnja', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (128, N'Novi Bečej', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (129, N'Novi Kneževac', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (130, N'Novi Pazar', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (131, N'Novi Sad-grad', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (132, N'Novo Brdo', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (133, N'Obilić', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (134, N'Opovo', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (135, N'Osečina', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (136, N'Odžaci', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (137, N'Pančevo', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (138, N'Paraćin', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (139, N'Petrovac', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (140, N'Peć', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (141, N'Pećinci', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (142, N'Pirot', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (143, N'Plandište', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (144, N'Podujevo', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (145, N'Požarevac', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (146, N'Požega', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (147, N'Preševo', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (148, N'Priboj', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (149, N'Prizren', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (150, N'Prijepolje', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (151, N'Priština-grad', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (152, N'Prokuplje', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (153, N'Ražanj', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (154, N'Rača', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (155, N'Raška', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (156, N'Rekovac', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (157, N'Ruma', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (158, N'Svilajnac', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (159, N'Svrljig', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (160, N'Sečanj', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (161, N'Sjenica', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (162, N'Smederevo', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (163, N'Smederevska Palanka', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (164, N'Sokobanja', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (165, N'Sombor', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (166, N'Srbobran', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (167, N'Sremska Mitrovica', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (168, N'Sremski Karlovci', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (169, N'Stara Pazova', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (170, N'Subotica', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (171, N'Suva Reka', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (172, N'Surdulica', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (173, N'Temerin', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (174, N'Titel', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (175, N'Topola', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (176, N'Trgovište', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (177, N'Trstenik', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (178, N'Tutin', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (179, N'Ćićevac', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (180, N'Ćuprija', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (181, N'Ub', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (182, N'Užice', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (183, N'Uroševac', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (184, N'Čajetina', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (185, N'Čačak', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (186, N'Čoka', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (187, N'Šabac', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (188, N'Šid', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (189, N'Štimlje', 1)
INSERT INTO [dbo].[Opstinas] ([Id], [NazivOpstine], [Aktivan]) VALUES (190, N'Štrpce', 1)
SET IDENTITY_INSERT [dbo].[Opstinas] OFF
