SET IDENTITY_INSERT [dbo].[Relacijas] ON
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Aktivan]) VALUES (1, N'Ada AS - Bačko Petrovo Selo - Bečej AS', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Aktivan]) VALUES (2, N'Ada AS - Senta AS', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Aktivan]) VALUES (3, N'Aleksandrovac AS - Brus AS', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Aktivan]) VALUES (4, N'Aleksandrovac AS - Ploča - Jošanička Banja', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Aktivan]) VALUES (5, N'Aleksandrovac AS - Velika Vrbnica - Kruševac AS', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Aktivan]) VALUES (6, N'Aleksandrovo - Balajnac - okretnica', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Aktivan]) VALUES (7, N'Aleksinac AS - Beograd AS (autoput)', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Aktivan]) VALUES (8, N'Aleksinac AS - Ćuprija AS (autoput)', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Aktivan]) VALUES (9, N'Aleksinac AS - Gornja Toponica', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Aktivan]) VALUES (10, N'Aleksinac AS - Jagodina AS', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Aktivan]) VALUES (11, N'Aleksinac AS - Mozgovo - Okretnica', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Aktivan]) VALUES (12, N'Aleksinac AS - Niš AS (autoput)', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Aktivan]) VALUES (13, N'Aleksinac AS - Paraćin AS (autoput)', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Aktivan]) VALUES (14, N'Aleksinac AS - Praskovče - Ražanj AS', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Aktivan]) VALUES (15, N'Aleksinac AS - Ražanj AS (autoput)', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Aktivan]) VALUES (16, N'Aleksinac AS - Sokobanja AS', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Aktivan]) VALUES (17, N'Aleksinac AS - Tešica - Gornja Toponica - Niš AS', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Aktivan]) VALUES (18, N'Aleksinac AS - Varvarin AS (autoput)', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Aktivan]) VALUES (19, N'Aleksinac AS - Vitkovac - Kaonik R', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Aktivan]) VALUES (20, N'Alibunar AS - Dobrica', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Aktivan]) VALUES (21, N'Alibunar AS - Pančevo AS', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Aktivan]) VALUES (22, N'Alibunar AS - Plandište AS', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Aktivan]) VALUES (23, N'Alibunar AS - Uljma - Vršac AS', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Aktivan]) VALUES (24, N'Apatin AS - Kupusina - Sombor AS', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Aktivan]) VALUES (25, N'Apatin AS - Prigrevica', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Aktivan]) VALUES (26, N'Apatin AS - Sombor AS', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Aktivan]) VALUES (27, N'Aranđelovac AS - Darosava - Belanovica AS', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Aktivan]) VALUES (28, N'Aranđelovac AS - Jelovik - Dragolj', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Aktivan]) VALUES (29, N'Aranđelovac AS - Krćevac - Mladenovac AS', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Aktivan]) VALUES (30, N'Aranđelovac AS - Kruševica - Bistrica - centar - Lazarevac AS', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Aktivan]) VALUES (31, N'Aranđelovac AS - Orašac - Mladenovac AS', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Aktivan]) VALUES (32, N'Aranđelovac AS - Ranilović - Rogača', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Aktivan]) VALUES (33, N'Aranđelovac AS - Rudovci - Lazarevac AS', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Aktivan]) VALUES (34, N'Aranđelovac AS - Topola AS', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Aktivan]) VALUES (35, N'Aranđelovac AS - Venčane - Strmovo', 1)
SET IDENTITY_INSERT [dbo].[Relacijas] OFF
