SET IDENTITY_INSERT [dbo].[Relacijas] ON
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1, N'Ada AS - Bačko Petrovo Selo - Bečej AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (2, N'Ada AS - Senta AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (3, N'Aleksandrovac AS - Brus AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (4, N'Aleksandrovac AS - Ploča - Jošanička Banja', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (5, N'Aleksandrovac AS - Velika Vrbnica - Kruševac AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (6, N'Aleksandrovo - Balajnac - okretnica', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (7, N'Aleksinac AS - Beograd AS (autoput)', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (8, N'Aleksinac AS - Ćuprija AS (autoput)', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (9, N'Aleksinac AS - Gornja Toponica', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (10, N'Aleksinac AS - Jagodina AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (11, N'Aleksinac AS - Mozgovo - Okretnica', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (12, N'Aleksinac AS - Niš AS (autoput)', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (13, N'Aleksinac AS - Paraćin AS (autoput)', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (14, N'Aleksinac AS - Praskovče - Ražanj AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (15, N'Aleksinac AS - Ražanj AS (autoput)', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (16, N'Aleksinac AS - Sokobanja AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (17, N'Aleksinac AS - Tešica - Gornja Toponica - Niš AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (18, N'Aleksinac AS - Varvarin AS (autoput)', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (19, N'Aleksinac AS - Vitkovac - Kaonik R', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (20, N'Alibunar AS - Dobrica', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (21, N'Alibunar AS - Pančevo AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (22, N'Alibunar AS - Plandište AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (23, N'Alibunar AS - Uljma - Vršac AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (24, N'Apatin AS - Kupusina - Sombor AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (25, N'Apatin AS - Prigrevica', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (26, N'Apatin AS - Sombor AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (27, N'Aranđelovac AS - Darosava - Belanovica AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (28, N'Aranđelovac AS - Jelovik - Dragolj', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (29, N'Aranđelovac AS - Krćevac - Mladenovac AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (30, N'Aranđelovac AS - Kruševica - Bistrica - centar - Lazarevac AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (31, N'Aranđelovac AS - Orašac - Mladenovac AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (32, N'Aranđelovac AS - Ranilović - Rogača', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (33, N'Aranđelovac AS - Rudovci - Lazarevac AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (34, N'Aranđelovac AS - Topola AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (35, N'Aranđelovac AS - Venčane - Strmovo', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (36, N'Arilje AS - Ivanjica AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (37, N'Arilje AS - Milićevo Selo - Požega AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (38, N'Azanja - Vlaški Do - Dobri Do', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (39, N'Babušnica AS - Bela Palanka AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (40, N'Babušnica AS - Pirot AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (41, N'Babušnica AS - Vlasotince AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (42, N'Bač AS - Bođani', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (43, N'Bač AS - Deronje - Odžaci AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (44, N'Bač AS - Obrovac - Bačka Palanka AS ', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (45, N'Bačevci - Vrh polje - Ljubovija AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (46, N'Bačinački put - Dobri Do - raskrsnica - Smenderevska Palanka AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (47, N'Bačinački put - Mihajlovac - Ralja', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (48, N'Bačinački put - Selevac AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (49, N'Bačka Palanka AS - Mladenovo - Centar', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (50, N'Bačka Palanka AS - Novi Sad MAS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (51, N'Bačka Palanka AS - Obrovac - Bač AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (52, N'Bačka Palanka AS - Silbaš - Despotovo', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (53, N'Bačka Topola AS - Feketić - Vrbas AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (54, N'Bačka Topola AS - Mali Iđoš - Srbobran AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (55, N'Bačka Topola AS - Mileševo - Bečaj AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (56, N'Bačka Topola AS - Pačir - Bajmok -  centar', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (57, N'Bačka Topola AS - Stari Žednik - Subotica AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (58, N'Bačka Topola AS - Tornjoš I', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (59, N'Bačka Topola AS - Zobnatica - Subotica AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (60, N'Bački Petrovac AS - Maglić - Silbaš - Centar', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (61, N'Bački Petrovac AS - Novi Sad MAS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (62, N'Bački Petrovac AS - Ravno Selo - Despotovo - Centar', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (63, N'Bački Vinogradi - Horgoš - Kanjiža', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (64, N'Bački Vinogradi - Male Pijace', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (65, N'Bački Vinogradi - Subotica AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (66, N'Baćica - Delimeđe - Novi Pazar AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (67, N'Badovinci - centar - Bogatić AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (68, N'Badovinci - centar - Crnobarski salaš', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (69, N'Badovinci - centar - Zasavica - Sremska Mitrovica AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (70, N'Badovinci - centar - Prnjavor', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (71, N'Bagrdan - Batočina AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (72, N'Bagrdan - Donje Komarice', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (73, N'Bagrdan - Jagodina AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (74, N'Bajina Bašta AS - Kostojevići - Užice AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (75, N'Bajina Bašta AS - Ljubovija AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (76, N'Bajina Bašta AS - Pilica - Nikolica brdo - Užice AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (77, N'Bajina Bašta AS - Tara - hotel Omorika', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (78, N'Bajina Bašta AS - Valjevo AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (79, N'Bajmok - centar - Mišićevo - Subotica AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (80, N'Bajmok - centar - Pačir - Bačka Topola AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (81, N'Bajmok - Svetozar Miletić - Sombor AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (82, N'Balajnac - okretnica - Aleksandrovo', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (83, N'Banatski Karlovac - Uljma - Straža', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (84, N'Banatsko Karađorđevo - Banatski Dvor - Žitište', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (85, N'Banatsko Karađorđevo - Nova Crnja - Radojevo', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (86, N'Banatsko Karađorđevo - Torda - Bašaid', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (87, N'Banovo polje - Crna Bara - Bogatić AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (88, N'Banja Vrujci - Mionica', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (89, N'Banjani - Obrenovac AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (90, N'Banjska  rampa - Niška Banja', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (91, N'Bašaid - Kikinda AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (92, N'Bašaid - Torda - Banatsko Karađorđevo', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (93, N'Bašaid centar - Melenci - Zrenjanin AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (94, N'Batajnica - centar - Beograd AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (95, N'Batajnica - centar - Beograd Lasta', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (96, N'Batajnica - centar - Nova Pazova - El. Metal - Stara Pazova AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (97, N'Batajnica - centar - Stara Pazova AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (98, N'Batajnica - centar - Surduk - okretnica', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (99, N'Batajnica - centar -  Zemun - Kej oslobođenja', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (100, N'Batočina AS - Bagrdan', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (101, N'Batočina AS - Beograd AS (autoput)', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (102, N'Batočina AS - Crni Kao - Batočina AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (103, N'Batočina AS - Kijevo - Batočina AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (104, N'Batočina AS - Kragujevac AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (105, N'Batočina AS - Lapovo - Trafo - Lapovo AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (106, N'Batočina AS - Lapovo AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (107, N'Batočina AS - Niš AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (108, N'Batočina AS - Žirovnica - Kragujevac AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (109, N'Batušinac - Belotinac', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (110, N'Bečej AS - Bačko Petrovo Selo - Ada AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (111, N'Bečej AS - Mileševo - Bačka Topola AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (112, N'Bečej AS - Novi Bečej AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (113, N'Bečej AS - Srbobran AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (114, N'Bečej AS - Temerin - Novi Sad MAS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (115, N'Bela Crkva AS - Gaj - C - Kovin AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (116, N'Bela Crkva AS - Straža - Vršac AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (117, N'Bela Palanka AS - Babušnica AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (118, N'Bela Palanka AS - Beograd AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (119, N'Bela Palanka AS - Niš AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (120, N'Bela Palanka AS - Pirot AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1109, N'Belanovica AS - Darosava - Aranđelovac AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1110, N'Beloljin - Blace AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1111, N'Beloljin - Kuršumlija AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1112, N'Beloljin - Prokuplje AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1113, N'Belotinac - Batušinac', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1114, N'Belotinac R - Perutina', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1115, N'Beočin selo - Okretnica - Rakovac - Odmaralište Novomont', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1116, N'Beograd AS - Aleksinac AS (autoput)', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1117, N'Beograd AS - Autokomanda - Požarevac AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1118, N'Beograd AS - Batajnica - centar', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1119, N'Beograd AS - Batočina AS (autoput)', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1120, N'Beograd AS - Bela Palanka As', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1121, N'Beograd AS - Brestovac AS (autoput)', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1122, N'Beograd AS - Ćićevac AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1123, N'Beograd AS - Ćuprija AS (autoput)', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1124, N'Beograd AS - Jagodina AS (autoput)', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1125, N'Beograd AS - Kolari (autoput)', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1126, N'Beograd AS - Kovin AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1127, N'Beograd AS - Kragujevac AS (autoput)', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1128, N'Beograd AS - Kruševac AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1129, N'Beograd AS - Lapovo AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1130, N'Beograd AS - Leskovac AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1131, N'Beograd AS - Lučani AS (ekspres)', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1132, N'Beograd AS - Mačvanska Mitrovica AS (autoputem)', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1133, N'Beograd AS - Meljak - Ćelije', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1134, N'Beograd AS - Mladenovac AS (autoput)', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1135, N'Beograd AS - Niš AS (autoput)', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1136, N'Beograd AS - Novi Sad MAS (autoput)', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1137, N'Beograd AS - Obrenovac AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1138, N'Beograd AS - Pančevo AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1139, N'Beograd AS - Paraćin AS (autoput)', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1140, N'Beograd AS - Pećinci - Ruma AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1141, N'Beograd AS - Pirot AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1142, N'Beograd AS - Požega AS (ekspres)', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1143, N'Beograd AS - Ražanj AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1144, N'Beograd AS - Ražanj AS (autoput)', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1145, N'Beograd AS - Sremska Mitrovica AS (autoput)', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1146, N'Beograd AS - Stepojevac - Ćelije', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1147, N'Beograd AS - Stragari - Medveđa - dom', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1148, N'Beograd AS - Svilajnac AS (autoput)', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1149, N'Beograd AS - Šabac AS (autoputem)', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1150, N'Beograd AS - Tehnopromet - Bor AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1151, N'Beograd AS - Trstenik AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1152, N'Beograd AS - Užice AS (ekspres)', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1153, N'Beograd AS - Varvarin AS (autoput)', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1154, N'Beograd AS - Velika Plana AS (autoput)', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1155, N'Beograd AS - Vladičin Han AS (autoput)', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1156, N'Beograd AS - Voganj - Smederevo AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1157, N'Beograd AS - Vranje AS (autoput)', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1158, N'Beograd AS - Zaječar AS (ekspres)', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1159, N'Beograd AS - Zemun - Pošta - Novi Sad MAS (autoput)', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1160, N'Beograd AS - Zlatibor - Nova Varoš AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1161, N'Beograd AS - Zrenjanin AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1162, N'Beograd AS - Žabari AS (autoput)', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1163, N'Beograd Lasta - Barajevo - Venčane', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1164, N'Beograd Lasta - Batajnica - centar', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1165, N'Beograd Lasta - Bubanj potok - Grocka - Smederevo AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1166, N'Beograd Lasta - Cvetkova kafana - Smederevo AS', N'Ne znam kojoj opštini pripada Cvetkova kafana. Nisam uneo dalje', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1167, N'Beograd Lasta - Dunva stanica - Pančevo AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1168, N'Beograd Lasta - Krnješevci - Deč - Ašanja - Kupinovo - Donji Tovarnik', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1169, N'Beograd Lasta - Kukujevci - Šid AS', N'', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1170, N'Beograd Lasta - Lajkovac AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1171, N'Beograd Lasta - Mihajlovac - Smederevska Palanka AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1172, N'Beograd Lasta - Mladenovac AS (autoput)', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1173, N'Crnobarski salaš - Badovinci - centar', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1174, N'Crnobarski salaš - Klenje', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1175, N'Crvena Kafana - Provo - Crvena Kafana', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1176, N'Crvenka AS - Kruščić', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1177, N'Crvenka AS - Kula AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1178, N'Crvenka AS - Sivac AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1179, N'Čačak AS - Beograd AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1180, N'Čačak AS - Brđani - Gornji Milanovac AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1181, N'Čačak AS - Gornja Gorevnica - Srezojevci', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1182, N'Đala - Srpski Krstur - Novi Kneževac AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1183, N'Erdevik - Čalma - Sremska Mitrovica AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1184, N'Čačak AS - Guča AS (Novi put)', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1185, N'Farkaždin - Sakule - Opovo - Beograd Lasta', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1186, N'Beograd Lasta - Obrenovac AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1187, N'Beograd Lasta - Opovo - Sakule - Idvor - Farkaždin', N'Proveri opštinu gde pripada Idvor (Kovačica ili Zrenjanin). Treba Kovačica, proveri da li je nešto vezano na Idvor (ZR) i obriši stajalište', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1188, N'Debrc R - Banjani - Ub AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1189, N'Beograd Lasta - Opovo AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1190, N'Beograd Lasta - Sefkerin - Glogonj okretnica', N'Ne znam kojoj opštini pripada stajalište Vrbovno Most Tamiš', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1191, N'Debrec R - Obrenovac AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1192, N'Beograd Lasta - Selevac - Smederevska Palanka AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1193, N'Debrc R - Šabac AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1194, N'Beograd Lasta - Šimanovci - Deč - Pećinci - Brestač', N'', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1195, N'Beograd Lasta - Zemun - Kej oslobođenja - Batajnica - centar', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1196, N'Blace AS - Beloljin', N'', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1197, N'Blace AS - Gornje Svrače - Prokuplje AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1198, N'Blace AS - Grgure - Kuršumlija AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1199, N'Blace AS - Kruševac AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1200, N'Blace AS - Zlatari - Kruševac AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1201, N'Blaževo - Brus AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1202, N'Bočar - Centar - Novo Miloševo - Novi Bečej AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1203, N'Bođani - Bač AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1204, N'Bogatić AS - Badovinci centar', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1205, N'Bogatić AS - Crna Bara - Banovo polje', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1206, N'Bogatić AS - Crnobarski salaš - Badovinci - centar', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1207, N'Bogatić AS - Dublje - centar - Šabac AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1208, N'Bogatić AS - Mačvanska Mitrovica AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1209, N'Bogatić AS - Mačvanski Metković - Glušci - centar', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1210, N'Bojnik AS - Doljevac R', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1211, N'Bojnik AS - Đinđuša - Leskovac AS', N'', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1212, N'Bojnik AS - Lebane AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1213, N'Boljevac - Šarbanovac - Bor AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1214, N'Boljevac AS - Paraćin AS (Gkavačkim putem)', N'', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1215, N'Boljevac AS - Valakonje - Sumrakovac - R', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1216, N'Boljevac AS - Zlot - Bor AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1217, N'Boljevac AS - Zvezdan - Zaječar AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1218, N'Bor AS - Boljevac AS - Beograd AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1219, N'Bor AS - Brestovac R - Beograd AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1220, N'Bor AS - Miloševa Kula - Donji Milanovac AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1221, N'Bor AS - Popovica - Brza Palanka', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1222, N'Bor AS - Rgotina - Zaječar AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1223, N'Bor AS - Šarbanovac - Boljevac AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1224, N'Bor AS - Šarbanovac - Sumrakovac', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1225, N'Bor AS - Šarbanovac - Zaječar AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1226, N'Bor AS - Zaječar AS (preko Nikoličeva)', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1227, N'Bor AS - Zlot - Boljevac AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1228, N'Bor AS - Žagubica AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1229, N'Borač - Kragujevac AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1230, N'Bosilegrad AS - Surdulica AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1231, N'Brestač - Sremski Mihaljevci - Deč - Beograd Lasta', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1232, N'Brestovac AS - Beograd AS (autoput)', N'str 201', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1233, N'Čačak AS - Guča AS (Stari put)', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1234, N'Čačak AS - Jasen - Šiljkovica - Šumljakovina', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1235, N'Čačak AS - Konjevići - Brđani - Gornji Milanovac AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1236, N'Čačak AS - Ljig AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1237, N'Debrec R - Vladimirci AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1238, N'Deč - Šimanovci - Stara Pazova AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1239, N'Despotovac AS - Balajnac - Veliki Popović', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1240, N'Despotovac AS - Medveđa - Svilajnac AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1241, N'Despotovac AS - Resavica AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1242, N'Despotovac AS - Vodna - Krepoljin', N'Pero, kakva ti je Slađa u glavi?! Nije Slađa nego Sladaja', 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1243, N'Despotovo - centar - Pivnice - Lovački dom', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1244, N'Despotovo - Centar - Pivnice - Lovački dom', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1245, N'Despotovo - Centar - Ratkovo - Odžaci AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1246, N'Despotovo - Centar - Ravno Selo - Bački Petrovac AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1247, N'Despotovo - Centar - Ravno Selo - Zmajevo - centar', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1248, N'Despotovo - Centar - Savino Selo - Vrbas AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1249, N'Čačak AS - Markovica - Lučani AS', NULL, 1)
INSERT INTO [dbo].[Relacijas] ([Id], [Naziv], [Napomena], [Aktivan]) VALUES (1250, N'Čačak AS - Ovčar Banja - Požega AS', NULL, 1)
SET IDENTITY_INSERT [dbo].[Relacijas] OFF
